/*
 * Generated by gloam 0.4.8. DO NOT EDIT.
 *
 *   gloam --api gl:core,gles2,egl --merge --fetch --out-path gl-egl --quiet c --alias --loader
 *
 * Extensions: all (224 included)
 *
 * Copyright (c) 2026 Steven Noonan
 * SPDX-License-Identifier: MIT
 *
 * Portions derived from Khronos Group XML API Registry specifications.
 * Copyright (c) 2013-2026 The Khronos Group Inc.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Includes extensions from the ANGLE project (gl_angle_ext.xml, egl_angle_ext.xml).
 * Copyright (c) 2026 Google Inc.
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include <gloam/egl.h>

#if defined(__CYGWIN__) || defined(_WIN32)
#  ifndef WIN32_LEAN_AND_MEAN
#    define WIN32_LEAN_AND_MEAN
#  endif
#  undef APIENTRY       /* fix macro redefinition warning */
#  include <windows.h>  /* LoadLibrary, GetProcAddress */
#else
#  include <dlfcn.h> /* dlopen, dlsym, dlclose */
#endif

#include <stdlib.h>  /* calloc, free    */
#include <stddef.h>
#include <stdio.h>   /* sscanf          */
#include <string.h>  /* strlen, strncmp */

#if defined(__x86_64__) || defined(__i386__) || defined(_M_IX86) || defined(_M_X64)
#  ifndef XXH_VECTOR
#    define XXH_VECTOR XXH_SSE2
#  endif
#  include <immintrin.h>
#elif defined(__aarch64__) || defined(__arm__) || defined(_M_ARM) || defined(_M_ARM64)
#  ifndef XXH_VECTOR
#    define XXH_VECTOR XXH_NEON
#  endif
#  include <arm_neon.h>
#endif
#ifndef GLOAM_EXTERNAL_XXHASH
#  define XXH_INLINE_ALL
#  define XXH_NO_STREAM
#endif
#include "xxhash.h"

#ifndef GLOAM_IMPL_UTIL_C_
#define GLOAM_IMPL_UTIL_C_

/* MSVC vs GCC/Clang sscanf */
#ifdef _MSC_VER
#  define GLOAM_IMPL_UTIL_SSCANF sscanf_s
#else
#  define GLOAM_IMPL_UTIL_SSCANF sscanf
#endif

/* GLOAM_NO_INLINE — suppress inlining on functions that should stay out of
 * the hot path (sort, hash, etc.) to avoid code bloat at call sites.
 */
#ifdef _MSC_VER
#  define GLOAM_NO_INLINE __declspec(noinline)
#else
#  define GLOAM_NO_INLINE __attribute__((noinline))
#endif

#define GLOAM_ARRAYSIZE(x) (sizeof(x) / sizeof((x)[0]))
#define GLOAM_UNUSED(x)    ((void)(x))

/* Contiguous run of pfnArray slots belonging to one feature or extension.
 * Used by the range-based PFN loading loop.
 */
typedef struct {
    uint16_t extension; /* index into featArray or extArray  */
    uint16_t start;     /* first pfnArray index in this run  */
    uint16_t count;     /* number of consecutive slots       */
} GloamPfnRange_t;

/* Bijective alias pair: if canonical slot is null but secondary is loaded
 * (or vice versa), the loaded pointer is propagated to both slots.
 */
typedef struct {
    uint16_t first;  /* canonical (shortest name) pfnArray index */
    uint16_t second; /* alias pfnArray index                     */
} GloamAliasPair_t;

#endif /* GLOAM_IMPL_UTIL_C_ */


#ifndef GLOAM_IMPL_HASHSEARCH_C_
#define GLOAM_IMPL_HASHSEARCH_C_

/* gloam_sort_hashes — in-place Shellsort on a uint64_t array.
 *
 * Ciura (2001) gap sequence.  Gaps larger than n are skipped at runtime so
 * small arrays (< 10 extensions) take only a couple of passes.  No heap
 * allocation; code size is ~80 bytes on x86-64.
 */
GLOAM_NO_INLINE static void gloam_sort_hashes(uint64_t *a, size_t n)
{
    static const size_t kGaps[] = { 701, 301, 132, 57, 23, 10, 4, 1 };
    size_t gi = 0;
    if (!a || n < 2) return;
    /* Skip gaps that are larger than the array. */
    while (gi < GLOAM_ARRAYSIZE(kGaps) && kGaps[gi] >= n) ++gi;
    for (; gi < GLOAM_ARRAYSIZE(kGaps); ++gi) {
        size_t gap = kGaps[gi], i;
        for (i = gap; i < n; ++i) {
            uint64_t v = a[i];
            size_t j = i;
            while (j >= gap && a[j - gap] > v) {
                a[j] = a[j - gap];
                j -= gap;
            }
            a[j] = v;
        }
    }
}

/* gloam_hash_search — binary search for `target` in a sorted uint64_t array.
 * Returns 1 if found, 0 otherwise.
 */
GLOAM_NO_INLINE static int gloam_hash_search(const uint64_t *arr, uint32_t size, uint64_t target)
{
    int32_t lo = 0, hi = (int32_t)size - 1;
    while (lo <= hi) {
        int32_t mid = lo + (hi - lo) / 2;
        if (arr[mid] == target) return 1;
        if (arr[mid] < target)  lo = mid + 1;
        else                    hi = mid - 1;
    }
    return 0;
}

/* gloam_hash_string — hash a NUL-terminated string with XXH3-64.
 * The same algorithm is used at generator time to pre-bake kExtHashes[],
 * guaranteeing that driver-reported names and the embedded table match.
 */
GLOAM_NO_INLINE static uint64_t gloam_hash_string(const char *str, size_t length)
{
    return XXH3_64bits(str, length);
}

/* ---- Extension string tokenizer ------------------------------------------
   Two-pass tokenize-and-hash for space-separated extension strings (GL, EGL,
   GLX, WGL).  First pass counts tokens, second pass hashes them.  Result is
   sorted for binary search in find_extensions. */
GLOAM_NO_INLINE static int gloam_hash_ext_string(const char *ext_str, uint64_t **out_exts, uint32_t *out_num_exts)
{
    const char *cur, *next;
    uint64_t *exts = NULL;
    uint32_t num_exts = 0, j;

    for (j = 0; j < 2; ++j) {
        num_exts = 0;
        cur  = ext_str;
        next = cur + strcspn(cur, " ");
        while (1) {
            size_t len;
            cur += strspn(cur, " ");
            if (!cur[0])
                break;
            len = (size_t)(next - cur);
            if (exts)
                exts[num_exts] = gloam_hash_string(cur, len);
            ++num_exts;
            cur  = next + strspn(next, " ");
            next = cur  + strcspn(cur,  " ");
        }
        if (!exts) {
            exts = (uint64_t *)calloc(num_exts, sizeof(uint64_t));
            if (!exts)
                return 0;
        }
    }

    gloam_sort_hashes(exts, num_exts);
    *out_exts     = exts;
    *out_num_exts = num_exts;
    return 1;
}
#endif /* GLOAM_IMPL_HASHSEARCH_C_ */


/* ---- Global context (zero-initialised at program startup) ---------------- */
#ifdef __cplusplus
GloamEGLContext gloam_egl_context = {};
#else
GloamEGLContext gloam_egl_context = { 0 };
#endif

/* ---- Function name table -------------------------------------------------
 * Command names stored as a single NUL-terminated string blob with a parallel
 * offset table for O(1) indexing. This avoids one pointer (8 bytes on 64-bit)
 * plus one relocation entry (~24 bytes in PIC builds) per command compared to
 * the traditional const char * const [] approach.
 */
static const uint32_t kFnCount_EGL = 182;

static const char kFnNameData_EGL[] =
    /*     0 */ "eglChooseConfig\0"
    /*    16 */ "eglCopyBuffers\0"
    /*    31 */ "eglCreateContext\0"
    /*    48 */ "eglCreatePbufferSurface\0"
    /*    72 */ "eglCreatePixmapSurface\0"
    /*    95 */ "eglCreateWindowSurface\0"
    /*   118 */ "eglDestroyContext\0"
    /*   136 */ "eglDestroySurface\0"
    /*   154 */ "eglGetConfigAttrib\0"
    /*   173 */ "eglGetConfigs\0"
    /*   187 */ "eglGetCurrentDisplay\0"
    /*   208 */ "eglGetCurrentSurface\0"
    /*   229 */ "eglGetDisplay\0"
    /*   243 */ "eglGetError\0"
    /*   255 */ "eglGetProcAddress\0"
    /*   273 */ "eglInitialize\0"
    /*   287 */ "eglMakeCurrent\0"
    /*   302 */ "eglQueryContext\0"
    /*   318 */ "eglQueryString\0"
    /*   333 */ "eglQuerySurface\0"
    /*   349 */ "eglSwapBuffers\0"
    /*   364 */ "eglTerminate\0"
    /*   377 */ "eglWaitGL\0"
    /*   387 */ "eglWaitNative\0"
    /*   401 */ "eglBindTexImage\0"
    /*   417 */ "eglReleaseTexImage\0"
    /*   436 */ "eglSurfaceAttrib\0"
    /*   453 */ "eglSwapInterval\0"
    /*   469 */ "eglBindAPI\0"
    /*   480 */ "eglCreatePbufferFromClientBuffer\0"
    /*   513 */ "eglQueryAPI\0"
    /*   525 */ "eglReleaseThread\0"
    /*   542 */ "eglWaitClient\0"
    /*   556 */ "eglGetCurrentContext\0"
    /*   577 */ "eglClientWaitSync\0"
    /*   595 */ "eglCreateImage\0"
    /*   610 */ "eglCreatePlatformPixmapSurface\0"
    /*   641 */ "eglCreatePlatformWindowSurface\0"
    /*   672 */ "eglCreateSync\0"
    /*   686 */ "eglDestroyImage\0"
    /*   702 */ "eglDestroySync\0"
    /*   717 */ "eglGetPlatformDisplay\0"
    /*   739 */ "eglGetSyncAttrib\0"
    /*   756 */ "eglWaitSync\0"
    /*   768 */ "eglSetBlobCacheFuncsANDROID\0"
    /*   796 */ "eglCreateNativeClientBufferANDROID\0"
    /*   831 */ "eglGetNativeClientBufferANDROID\0"
    /*   863 */ "eglDupNativeFenceFDANDROID\0"
    /*   890 */ "eglPresentationTimeANDROID\0"
    /*   917 */ "eglGetCompositorTimingANDROID\0"
    /*   947 */ "eglGetCompositorTimingSupportedANDROID\0"
    /*   986 */ "eglGetFrameTimestampSupportedANDROID\0"
    /*  1023 */ "eglGetFrameTimestampsANDROID\0"
    /*  1052 */ "eglGetNextFrameIdANDROID\0"
    /*  1077 */ "eglQuerySurfacePointerANGLE\0"
    /*  1105 */ "eglGetMscRateANGLE\0"
    /*  1124 */ "eglClientSignalSyncEXT\0"
    /*  1147 */ "eglQueryDevicesEXT\0"
    /*  1166 */ "eglQueryDeviceAttribEXT\0"
    /*  1190 */ "eglQueryDeviceStringEXT\0"
    /*  1214 */ "eglQueryDisplayAttribEXT\0"
    /*  1239 */ "eglQueryDmaBufFormatsEXT\0"
    /*  1264 */ "eglQueryDmaBufModifiersEXT\0"
    /*  1291 */ "eglGetOutputLayersEXT\0"
    /*  1313 */ "eglGetOutputPortsEXT\0"
    /*  1334 */ "eglOutputLayerAttribEXT\0"
    /*  1358 */ "eglOutputPortAttribEXT\0"
    /*  1381 */ "eglQueryOutputLayerAttribEXT\0"
    /*  1410 */ "eglQueryOutputLayerStringEXT\0"
    /*  1439 */ "eglQueryOutputPortAttribEXT\0"
    /*  1467 */ "eglQueryOutputPortStringEXT\0"
    /*  1495 */ "eglCreatePlatformPixmapSurfaceEXT\0"
    /*  1529 */ "eglCreatePlatformWindowSurfaceEXT\0"
    /*  1563 */ "eglGetPlatformDisplayEXT\0"
    /*  1588 */ "eglStreamConsumerOutputEXT\0"
    /*  1615 */ "eglSwapBuffersWithDamageEXT\0"
    /*  1643 */ "eglUnsignalSyncEXT\0"
    /*  1662 */ "eglCreatePixmapSurfaceHI\0"
    /*  1687 */ "eglCreateSync64KHR\0"
    /*  1706 */ "eglDebugMessageControlKHR\0"
    /*  1732 */ "eglLabelObjectKHR\0"
    /*  1750 */ "eglQueryDebugKHR\0"
    /*  1767 */ "eglQueryDisplayAttribKHR\0"
    /*  1792 */ "eglClientWaitSyncKHR\0"
    /*  1813 */ "eglCreateSyncKHR\0"
    /*  1830 */ "eglDestroySyncKHR\0"
    /*  1848 */ "eglGetSyncAttribKHR\0"
    /*  1868 */ "eglCreateImageKHR\0"
    /*  1886 */ "eglDestroyImageKHR\0"
    /*  1905 */ "eglLockSurfaceKHR\0"
    /*  1923 */ "eglUnlockSurfaceKHR\0"
    /*  1943 */ "eglQuerySurface64KHR\0"
    /*  1964 */ "eglSetDamageRegionKHR\0"
    /*  1986 */ "eglSignalSyncKHR\0"
    /*  2003 */ "eglCreateStreamKHR\0"
    /*  2022 */ "eglDestroyStreamKHR\0"
    /*  2042 */ "eglQueryStreamKHR\0"
    /*  2060 */ "eglQueryStreamu64KHR\0"
    /*  2081 */ "eglStreamAttribKHR\0"
    /*  2100 */ "eglCreateStreamAttribKHR\0"
    /*  2125 */ "eglQueryStreamAttribKHR\0"
    /*  2149 */ "eglSetStreamAttribKHR\0"
    /*  2171 */ "eglStreamConsumerAcquireAttribKHR\0"
    /*  2205 */ "eglStreamConsumerReleaseAttribKHR\0"
    /*  2239 */ "eglStreamConsumerAcquireKHR\0"
    /*  2267 */ "eglStreamConsumerGLTextureExternalKHR\0"
    /*  2305 */ "eglStreamConsumerReleaseKHR\0"
    /*  2333 */ "eglCreateStreamFromFileDescriptorKHR\0"
    /*  2370 */ "eglGetStreamFileDescriptorKHR\0"
    /*  2400 */ "eglQueryStreamTimeKHR\0"
    /*  2422 */ "eglCreateStreamProducerSurfaceKHR\0"
    /*  2456 */ "eglSwapBuffersWithDamageKHR\0"
    /*  2484 */ "eglWaitSyncKHR\0"
    /*  2499 */ "eglCreateDRMImageMESA\0"
    /*  2521 */ "eglExportDRMImageMESA\0"
    /*  2543 */ "eglExportDMABUFImageMESA\0"
    /*  2568 */ "eglExportDMABUFImageQueryMESA\0"
    /*  2598 */ "eglGetDisplayDriverConfig\0"
    /*  2624 */ "eglGetDisplayDriverName\0"
    /*  2648 */ "eglSwapBuffersRegionNOK\0"
    /*  2672 */ "eglSwapBuffersRegion2NOK\0"
    /*  2697 */ "eglQueryNativeDisplayNV\0"
    /*  2721 */ "eglQueryNativePixmapNV\0"
    /*  2744 */ "eglQueryNativeWindowNV\0"
    /*  2767 */ "eglPostSubBufferNV\0"
    /*  2786 */ "eglStreamConsumerGLTextureExternalAttribsNV\0"
    /*  2830 */ "eglQueryStreamConsumerEventNV\0"
    /*  2860 */ "eglStreamAcquireImageNV\0"
    /*  2884 */ "eglStreamImageConsumerConnectNV\0"
    /*  2916 */ "eglStreamReleaseImageNV\0"
    /*  2940 */ "eglStreamFlushNV\0"
    /*  2957 */ "eglQueryDisplayAttribNV\0"
    /*  2981 */ "eglQueryStreamMetadataNV\0"
    /*  3006 */ "eglSetStreamMetadataNV\0"
    /*  3029 */ "eglResetStreamNV\0"
    /*  3046 */ "eglCreateStreamSyncNV\0"
    /*  3068 */ "eglClientWaitSyncNV\0"
    /*  3088 */ "eglCreateFenceSyncNV\0"
    /*  3109 */ "eglDestroySyncNV\0"
    /*  3126 */ "eglFenceNV\0"
    /*  3137 */ "eglGetSyncAttribNV\0"
    /*  3156 */ "eglSignalSyncNV\0"
    /*  3172 */ "eglGetSystemTimeFrequencyNV\0"
    /*  3200 */ "eglGetSystemTimeNV\0"
    /*  3219 */ "eglCompositorBindTexWindowEXT\0"
    /*  3249 */ "eglCompositorSetContextAttributesEXT\0"
    /*  3286 */ "eglCompositorSetContextListEXT\0"
    /*  3317 */ "eglCompositorSetSizeEXT\0"
    /*  3341 */ "eglCompositorSetWindowAttributesEXT\0"
    /*  3377 */ "eglCompositorSetWindowListEXT\0"
    /*  3407 */ "eglCompositorSwapPolicyEXT\0"
    /*  3434 */ "eglQuerySupportedCompressionRatesEXT\0"
    /*  3471 */ "eglBindWaylandDisplayWL\0"
    /*  3495 */ "eglQueryWaylandBufferWL\0"
    /*  3519 */ "eglUnbindWaylandDisplayWL\0"
    /*  3545 */ "eglCreateWaylandBufferFromImageWL\0"
    /*  3579 */ "eglQueryDeviceBinaryEXT\0"
    /*  3603 */ "eglDestroyDisplayEXT\0"
    /*  3624 */ "eglCreateDeviceANGLE\0"
    /*  3645 */ "eglReleaseDeviceANGLE\0"
    /*  3667 */ "eglQueryDisplayAttribANGLE\0"
    /*  3694 */ "eglQueryStringiANGLE\0"
    /*  3715 */ "eglAcquireExternalContextANGLE\0"
    /*  3746 */ "eglReleaseExternalContextANGLE\0"
    /*  3777 */ "eglCreateStreamProducerD3DTextureANGLE\0"
    /*  3816 */ "eglStreamPostD3DTextureANGLE\0"
    /*  3845 */ "eglGetSyncValuesCHROMIUM\0"
    /*  3870 */ "eglProgramCacheGetAttribANGLE\0"
    /*  3900 */ "eglProgramCachePopulateANGLE\0"
    /*  3929 */ "eglProgramCacheQueryANGLE\0"
    /*  3955 */ "eglProgramCacheResizeANGLE\0"
    /*  3982 */ "eglWaitUntilWorkScheduledANGLE\0"
    /*  4013 */ "eglPrepareSwapBuffersANGLE\0"
    /*  4040 */ "eglForceGPUSwitchANGLE\0"
    /*  4063 */ "eglHandleGPUSwitchANGLE\0"
    /*  4087 */ "eglReacquireHighPowerGPUANGLE\0"
    /*  4117 */ "eglReleaseHighPowerGPUANGLE\0"
    /*  4145 */ "eglExportVkImageANGLE\0"
    /*  4167 */ "eglLockVulkanQueueANGLE\0"
    /*  4191 */ "eglUnlockVulkanQueueANGLE\0"
    /*  4217 */ "eglCopyMetalSharedEventANGLE\0"
    /*  4246 */ "eglSetValidationEnabledANGLE\0"
;
static const uint16_t kFnNameOffsets_EGL[] = {
    /*    0 */     0, /* eglChooseConfig */
    /*    1 */    16, /* eglCopyBuffers */
    /*    2 */    31, /* eglCreateContext */
    /*    3 */    48, /* eglCreatePbufferSurface */
    /*    4 */    72, /* eglCreatePixmapSurface */
    /*    5 */    95, /* eglCreateWindowSurface */
    /*    6 */   118, /* eglDestroyContext */
    /*    7 */   136, /* eglDestroySurface */
    /*    8 */   154, /* eglGetConfigAttrib */
    /*    9 */   173, /* eglGetConfigs */
    /*   10 */   187, /* eglGetCurrentDisplay */
    /*   11 */   208, /* eglGetCurrentSurface */
    /*   12 */   229, /* eglGetDisplay */
    /*   13 */   243, /* eglGetError */
    /*   14 */   255, /* eglGetProcAddress */
    /*   15 */   273, /* eglInitialize */
    /*   16 */   287, /* eglMakeCurrent */
    /*   17 */   302, /* eglQueryContext */
    /*   18 */   318, /* eglQueryString */
    /*   19 */   333, /* eglQuerySurface */
    /*   20 */   349, /* eglSwapBuffers */
    /*   21 */   364, /* eglTerminate */
    /*   22 */   377, /* eglWaitGL */
    /*   23 */   387, /* eglWaitNative */
    /*   24 */   401, /* eglBindTexImage */
    /*   25 */   417, /* eglReleaseTexImage */
    /*   26 */   436, /* eglSurfaceAttrib */
    /*   27 */   453, /* eglSwapInterval */
    /*   28 */   469, /* eglBindAPI */
    /*   29 */   480, /* eglCreatePbufferFromClientBuffer */
    /*   30 */   513, /* eglQueryAPI */
    /*   31 */   525, /* eglReleaseThread */
    /*   32 */   542, /* eglWaitClient */
    /*   33 */   556, /* eglGetCurrentContext */
    /*   34 */   577, /* eglClientWaitSync */
    /*   35 */   595, /* eglCreateImage */
    /*   36 */   610, /* eglCreatePlatformPixmapSurface */
    /*   37 */   641, /* eglCreatePlatformWindowSurface */
    /*   38 */   672, /* eglCreateSync */
    /*   39 */   686, /* eglDestroyImage */
    /*   40 */   702, /* eglDestroySync */
    /*   41 */   717, /* eglGetPlatformDisplay */
    /*   42 */   739, /* eglGetSyncAttrib */
    /*   43 */   756, /* eglWaitSync */
    /*   44 */   768, /* eglSetBlobCacheFuncsANDROID */
    /*   45 */   796, /* eglCreateNativeClientBufferANDROID */
    /*   46 */   831, /* eglGetNativeClientBufferANDROID */
    /*   47 */   863, /* eglDupNativeFenceFDANDROID */
    /*   48 */   890, /* eglPresentationTimeANDROID */
    /*   49 */   917, /* eglGetCompositorTimingANDROID */
    /*   50 */   947, /* eglGetCompositorTimingSupportedANDROID */
    /*   51 */   986, /* eglGetFrameTimestampSupportedANDROID */
    /*   52 */  1023, /* eglGetFrameTimestampsANDROID */
    /*   53 */  1052, /* eglGetNextFrameIdANDROID */
    /*   54 */  1077, /* eglQuerySurfacePointerANGLE */
    /*   55 */  1105, /* eglGetMscRateANGLE */
    /*   56 */  1124, /* eglClientSignalSyncEXT */
    /*   57 */  1147, /* eglQueryDevicesEXT */
    /*   58 */  1166, /* eglQueryDeviceAttribEXT */
    /*   59 */  1190, /* eglQueryDeviceStringEXT */
    /*   60 */  1214, /* eglQueryDisplayAttribEXT */
    /*   61 */  1239, /* eglQueryDmaBufFormatsEXT */
    /*   62 */  1264, /* eglQueryDmaBufModifiersEXT */
    /*   63 */  1291, /* eglGetOutputLayersEXT */
    /*   64 */  1313, /* eglGetOutputPortsEXT */
    /*   65 */  1334, /* eglOutputLayerAttribEXT */
    /*   66 */  1358, /* eglOutputPortAttribEXT */
    /*   67 */  1381, /* eglQueryOutputLayerAttribEXT */
    /*   68 */  1410, /* eglQueryOutputLayerStringEXT */
    /*   69 */  1439, /* eglQueryOutputPortAttribEXT */
    /*   70 */  1467, /* eglQueryOutputPortStringEXT */
    /*   71 */  1495, /* eglCreatePlatformPixmapSurfaceEXT */
    /*   72 */  1529, /* eglCreatePlatformWindowSurfaceEXT */
    /*   73 */  1563, /* eglGetPlatformDisplayEXT */
    /*   74 */  1588, /* eglStreamConsumerOutputEXT */
    /*   75 */  1615, /* eglSwapBuffersWithDamageEXT */
    /*   76 */  1643, /* eglUnsignalSyncEXT */
    /*   77 */  1662, /* eglCreatePixmapSurfaceHI */
    /*   78 */  1687, /* eglCreateSync64KHR */
    /*   79 */  1706, /* eglDebugMessageControlKHR */
    /*   80 */  1732, /* eglLabelObjectKHR */
    /*   81 */  1750, /* eglQueryDebugKHR */
    /*   82 */  1767, /* eglQueryDisplayAttribKHR */
    /*   83 */  1792, /* eglClientWaitSyncKHR */
    /*   84 */  1813, /* eglCreateSyncKHR */
    /*   85 */  1830, /* eglDestroySyncKHR */
    /*   86 */  1848, /* eglGetSyncAttribKHR */
    /*   87 */  1868, /* eglCreateImageKHR */
    /*   88 */  1886, /* eglDestroyImageKHR */
    /*   89 */  1905, /* eglLockSurfaceKHR */
    /*   90 */  1923, /* eglUnlockSurfaceKHR */
    /*   91 */  1943, /* eglQuerySurface64KHR */
    /*   92 */  1964, /* eglSetDamageRegionKHR */
    /*   93 */  1986, /* eglSignalSyncKHR */
    /*   94 */  2003, /* eglCreateStreamKHR */
    /*   95 */  2022, /* eglDestroyStreamKHR */
    /*   96 */  2042, /* eglQueryStreamKHR */
    /*   97 */  2060, /* eglQueryStreamu64KHR */
    /*   98 */  2081, /* eglStreamAttribKHR */
    /*   99 */  2100, /* eglCreateStreamAttribKHR */
    /*  100 */  2125, /* eglQueryStreamAttribKHR */
    /*  101 */  2149, /* eglSetStreamAttribKHR */
    /*  102 */  2171, /* eglStreamConsumerAcquireAttribKHR */
    /*  103 */  2205, /* eglStreamConsumerReleaseAttribKHR */
    /*  104 */  2239, /* eglStreamConsumerAcquireKHR */
    /*  105 */  2267, /* eglStreamConsumerGLTextureExternalKHR */
    /*  106 */  2305, /* eglStreamConsumerReleaseKHR */
    /*  107 */  2333, /* eglCreateStreamFromFileDescriptorKHR */
    /*  108 */  2370, /* eglGetStreamFileDescriptorKHR */
    /*  109 */  2400, /* eglQueryStreamTimeKHR */
    /*  110 */  2422, /* eglCreateStreamProducerSurfaceKHR */
    /*  111 */  2456, /* eglSwapBuffersWithDamageKHR */
    /*  112 */  2484, /* eglWaitSyncKHR */
    /*  113 */  2499, /* eglCreateDRMImageMESA */
    /*  114 */  2521, /* eglExportDRMImageMESA */
    /*  115 */  2543, /* eglExportDMABUFImageMESA */
    /*  116 */  2568, /* eglExportDMABUFImageQueryMESA */
    /*  117 */  2598, /* eglGetDisplayDriverConfig */
    /*  118 */  2624, /* eglGetDisplayDriverName */
    /*  119 */  2648, /* eglSwapBuffersRegionNOK */
    /*  120 */  2672, /* eglSwapBuffersRegion2NOK */
    /*  121 */  2697, /* eglQueryNativeDisplayNV */
    /*  122 */  2721, /* eglQueryNativePixmapNV */
    /*  123 */  2744, /* eglQueryNativeWindowNV */
    /*  124 */  2767, /* eglPostSubBufferNV */
    /*  125 */  2786, /* eglStreamConsumerGLTextureExternalAttribsNV */
    /*  126 */  2830, /* eglQueryStreamConsumerEventNV */
    /*  127 */  2860, /* eglStreamAcquireImageNV */
    /*  128 */  2884, /* eglStreamImageConsumerConnectNV */
    /*  129 */  2916, /* eglStreamReleaseImageNV */
    /*  130 */  2940, /* eglStreamFlushNV */
    /*  131 */  2957, /* eglQueryDisplayAttribNV */
    /*  132 */  2981, /* eglQueryStreamMetadataNV */
    /*  133 */  3006, /* eglSetStreamMetadataNV */
    /*  134 */  3029, /* eglResetStreamNV */
    /*  135 */  3046, /* eglCreateStreamSyncNV */
    /*  136 */  3068, /* eglClientWaitSyncNV */
    /*  137 */  3088, /* eglCreateFenceSyncNV */
    /*  138 */  3109, /* eglDestroySyncNV */
    /*  139 */  3126, /* eglFenceNV */
    /*  140 */  3137, /* eglGetSyncAttribNV */
    /*  141 */  3156, /* eglSignalSyncNV */
    /*  142 */  3172, /* eglGetSystemTimeFrequencyNV */
    /*  143 */  3200, /* eglGetSystemTimeNV */
    /*  144 */  3219, /* eglCompositorBindTexWindowEXT */
    /*  145 */  3249, /* eglCompositorSetContextAttributesEXT */
    /*  146 */  3286, /* eglCompositorSetContextListEXT */
    /*  147 */  3317, /* eglCompositorSetSizeEXT */
    /*  148 */  3341, /* eglCompositorSetWindowAttributesEXT */
    /*  149 */  3377, /* eglCompositorSetWindowListEXT */
    /*  150 */  3407, /* eglCompositorSwapPolicyEXT */
    /*  151 */  3434, /* eglQuerySupportedCompressionRatesEXT */
    /*  152 */  3471, /* eglBindWaylandDisplayWL */
    /*  153 */  3495, /* eglQueryWaylandBufferWL */
    /*  154 */  3519, /* eglUnbindWaylandDisplayWL */
    /*  155 */  3545, /* eglCreateWaylandBufferFromImageWL */
    /*  156 */  3579, /* eglQueryDeviceBinaryEXT */
    /*  157 */  3603, /* eglDestroyDisplayEXT */
    /*  158 */  3624, /* eglCreateDeviceANGLE */
    /*  159 */  3645, /* eglReleaseDeviceANGLE */
    /*  160 */  3667, /* eglQueryDisplayAttribANGLE */
    /*  161 */  3694, /* eglQueryStringiANGLE */
    /*  162 */  3715, /* eglAcquireExternalContextANGLE */
    /*  163 */  3746, /* eglReleaseExternalContextANGLE */
    /*  164 */  3777, /* eglCreateStreamProducerD3DTextureANGLE */
    /*  165 */  3816, /* eglStreamPostD3DTextureANGLE */
    /*  166 */  3845, /* eglGetSyncValuesCHROMIUM */
    /*  167 */  3870, /* eglProgramCacheGetAttribANGLE */
    /*  168 */  3900, /* eglProgramCachePopulateANGLE */
    /*  169 */  3929, /* eglProgramCacheQueryANGLE */
    /*  170 */  3955, /* eglProgramCacheResizeANGLE */
    /*  171 */  3982, /* eglWaitUntilWorkScheduledANGLE */
    /*  172 */  4013, /* eglPrepareSwapBuffersANGLE */
    /*  173 */  4040, /* eglForceGPUSwitchANGLE */
    /*  174 */  4063, /* eglHandleGPUSwitchANGLE */
    /*  175 */  4087, /* eglReacquireHighPowerGPUANGLE */
    /*  176 */  4117, /* eglReleaseHighPowerGPUANGLE */
    /*  177 */  4145, /* eglExportVkImageANGLE */
    /*  178 */  4167, /* eglLockVulkanQueueANGLE */
    /*  179 */  4191, /* eglUnlockVulkanQueueANGLE */
    /*  180 */  4217, /* eglCopyMetalSharedEventANGLE */
    /*  181 */  4246 /* eglSetValidationEnabledANGLE */
};
/* ---- Extension hash table ------------------------------------------------
   One XXH3-64 hash per extension, in extArray index order.
   Pre-baked at generator time with the same algorithm used at load time. */
static const uint64_t kExtHashes_EGL[] = {
    /*    0 */ 0x2253fd149000c540ULL, /* EGL_ANDROID_GLES_layers */
    /*    1 */ 0xb309a80c1c4fc565ULL, /* EGL_ANDROID_blob_cache */
    /*    2 */ 0x88e2a3925c1f8e55ULL, /* EGL_ANDROID_create_native_client_buffer */
    /*    3 */ 0xe9b9bdc50ba8347cULL, /* EGL_ANDROID_framebuffer_target */
    /*    4 */ 0xd7ca0046d8e351bdULL, /* EGL_ANDROID_front_buffer_auto_refresh */
    /*    5 */ 0x16293db95b2e6807ULL, /* EGL_ANDROID_get_frame_timestamps */
    /*    6 */ 0x1d1cb192f9421f4cULL, /* EGL_ANDROID_get_native_client_buffer */
    /*    7 */ 0xd2d9e8394e86467aULL, /* EGL_ANDROID_image_native_buffer */
    /*    8 */ 0x7e099daa98cd547eULL, /* EGL_ANDROID_native_fence_sync */
    /*    9 */ 0xe3ea63f73a400476ULL, /* EGL_ANDROID_presentation_time */
    /*   10 */ 0x3cc398fae4c2292eULL, /* EGL_ANDROID_recordable */
    /*   11 */ 0xd798697a922f4f6fULL, /* EGL_ANDROID_telemetry_hint */
    /*   12 */ 0xd59b8dcdd4961074ULL, /* EGL_ANGLE_colorspace_attribute_passthrough */
    /*   13 */ 0xe34ca55588e959e9ULL, /* EGL_ANGLE_context_virtualization */
    /*   14 */ 0x5ee453db857b3c29ULL, /* EGL_ANGLE_create_context_backwards_compatible */
    /*   15 */ 0xf2594fbcdfa3f545ULL, /* EGL_ANGLE_create_context_client_arrays */
    /*   16 */ 0x5f5244f40c7ef900ULL, /* EGL_ANGLE_create_context_extensions_enabled */
    /*   17 */ 0x4eac032f78eb1b97ULL, /* EGL_ANGLE_create_context_webgl_compatibility */
    /*   18 */ 0x3db394a57b9600edULL, /* EGL_ANGLE_create_surface_swap_interval */
    /*   19 */ 0x63dc3010a72f0f41ULL, /* EGL_ANGLE_d3d_share_handle_client_buffer */
    /*   20 */ 0x008d04b1748738c1ULL, /* EGL_ANGLE_d3d_texture_client_buffer */
    /*   21 */ 0xb9c6689d871a8219ULL, /* EGL_ANGLE_device_cgl */
    /*   22 */ 0xe481bb03dc3ffd32ULL, /* EGL_ANGLE_device_creation */
    /*   23 */ 0xa48498cc85257b13ULL, /* EGL_ANGLE_device_d3d */
    /*   24 */ 0xd669f40f3670027eULL, /* EGL_ANGLE_device_d3d11 */
    /*   25 */ 0x03032fed28369f5fULL, /* EGL_ANGLE_device_d3d9 */
    /*   26 */ 0x22f96d8668d51351ULL, /* EGL_ANGLE_device_eagl */
    /*   27 */ 0x00ba7a7f1c36e9e4ULL, /* EGL_ANGLE_device_metal */
    /*   28 */ 0x6f356a60670d8e5aULL, /* EGL_ANGLE_device_vulkan */
    /*   29 */ 0xc9df550ac4a1ec30ULL, /* EGL_ANGLE_direct_composition */
    /*   30 */ 0x00a9cc6756852346ULL, /* EGL_ANGLE_display_power_preference */
    /*   31 */ 0xed1190e49710ebdeULL, /* EGL_ANGLE_display_semaphore_share_group */
    /*   32 */ 0x2c22f1ea2f02edaeULL, /* EGL_ANGLE_display_texture_share_group */
    /*   33 */ 0xc03ef8c49f8daf6eULL, /* EGL_ANGLE_experimental_present_path */
    /*   34 */ 0x1160c225fe2a6bf5ULL, /* EGL_ANGLE_external_context_and_surface */
    /*   35 */ 0xf136655b938cfef7ULL, /* EGL_ANGLE_feature_control */
    /*   36 */ 0x18d0970ca7b4c268ULL, /* EGL_ANGLE_global_fence_sync */
    /*   37 */ 0x8247503770574a19ULL, /* EGL_ANGLE_iosurface_client_buffer */
    /*   38 */ 0x2050b7157f814d10ULL, /* EGL_ANGLE_keyed_mutex */
    /*   39 */ 0x3385337af72503e9ULL, /* EGL_ANGLE_memory_usage_report */
    /*   40 */ 0x1c79535a56a7c3daULL, /* EGL_ANGLE_metal_commands_scheduled_sync */
    /*   41 */ 0x5027858c4c30d226ULL, /* EGL_ANGLE_metal_create_context_ownership_identity */
    /*   42 */ 0x6e333abff6cec928ULL, /* EGL_ANGLE_metal_shared_event_sync */
    /*   43 */ 0xea85ee216b66aed6ULL, /* EGL_ANGLE_metal_texture_client_buffer */
    /*   44 */ 0x69ec6f07eb567773ULL, /* EGL_ANGLE_no_error */
    /*   45 */ 0x0e642f860b2670f4ULL, /* EGL_ANGLE_platform_angle */
    /*   46 */ 0xb3c6378facb30b47ULL, /* EGL_ANGLE_platform_angle_d3d */
    /*   47 */ 0x67363c4648bf01a6ULL, /* EGL_ANGLE_platform_angle_d3d11on12 */
    /*   48 */ 0x7404e65415e0cf49ULL, /* EGL_ANGLE_platform_angle_d3d_luid */
    /*   49 */ 0x5b49c1a91e2bcce3ULL, /* EGL_ANGLE_platform_angle_device_context_volatile_cgl */
    /*   50 */ 0xf27d356bb04d147dULL, /* EGL_ANGLE_platform_angle_device_context_volatile_eagl */
    /*   51 */ 0x1d4a1428061a339aULL, /* EGL_ANGLE_platform_angle_device_id */
    /*   52 */ 0xbe47353c1f13390bULL, /* EGL_ANGLE_platform_angle_device_type_egl */
    /*   53 */ 0xe9d3e98ad0d51659ULL, /* EGL_ANGLE_platform_angle_device_type_swiftshader */
    /*   54 */ 0x98c1482cf6675807ULL, /* EGL_ANGLE_platform_angle_metal */
    /*   55 */ 0x6ab80514da15b6f9ULL, /* EGL_ANGLE_platform_angle_null */
    /*   56 */ 0xb419931c39c7f38aULL, /* EGL_ANGLE_platform_angle_opengl */
    /*   57 */ 0xb2ad9cccda275eb4ULL, /* EGL_ANGLE_platform_angle_vulkan */
    /*   58 */ 0x76ecae883c1293e2ULL, /* EGL_ANGLE_platform_angle_vulkan_device_uuid */
    /*   59 */ 0x2d155ccb3d2e416dULL, /* EGL_ANGLE_platform_angle_webgpu */
    /*   60 */ 0xaf2ad94baa465742ULL, /* EGL_ANGLE_power_preference */
    /*   61 */ 0x41534601630f79ceULL, /* EGL_ANGLE_prepare_swap_buffers */
    /*   62 */ 0x15c4d55f4f359f01ULL, /* EGL_ANGLE_program_cache_control */
    /*   63 */ 0x655dcac0071412b7ULL, /* EGL_ANGLE_query_surface_pointer */
    /*   64 */ 0xbec48c7959021479ULL, /* EGL_ANGLE_robust_resource_initialization */
    /*   65 */ 0x9e02c97224491c29ULL, /* EGL_ANGLE_stream_producer_d3d_texture */
    /*   66 */ 0x460ce0075e78a2bdULL, /* EGL_ANGLE_surface_d3d_texture_2d_share_handle */
    /*   67 */ 0xa388335593ecba25ULL, /* EGL_ANGLE_surface_orientation */
    /*   68 */ 0xcbc83f2fb8143390ULL, /* EGL_ANGLE_sync_control_rate */
    /*   69 */ 0x9b7afb42d23ff24aULL, /* EGL_ANGLE_vulkan_display */
    /*   70 */ 0x3b9d20f1e7cea30cULL, /* EGL_ANGLE_vulkan_image */
    /*   71 */ 0x32f27a4c7977f1ccULL, /* EGL_ANGLE_wait_until_work_scheduled */
    /*   72 */ 0x584d724a2585416bULL, /* EGL_ANGLE_window_fixed_size */
    /*   73 */ 0x7fd85a1fe267fe03ULL, /* EGL_ANGLE_x11_visual */
    /*   74 */ 0x79e92599e5906543ULL, /* EGL_ARM_image_format */
    /*   75 */ 0xe6b4aba5bdfeb761ULL, /* EGL_ARM_implicit_external_sync */
    /*   76 */ 0xae00b1c9df43676fULL, /* EGL_ARM_pixmap_multisample_discard */
    /*   77 */ 0xff8aede3988df0ecULL, /* EGL_CHROMIUM_sync_control */
    /*   78 */ 0x9c662d7d2c258a50ULL, /* EGL_EXT_bind_to_front */
    /*   79 */ 0x2aa08328d074a816ULL, /* EGL_EXT_buffer_age */
    /*   80 */ 0xa31e0274c2bcafb4ULL, /* EGL_EXT_client_extensions */
    /*   81 */ 0x0391123aa67cc9fdULL, /* EGL_EXT_client_sync */
    /*   82 */ 0x7ad217dadabe87ccULL, /* EGL_EXT_compositor */
    /*   83 */ 0x7a089e984094346aULL, /* EGL_EXT_config_select_group */
    /*   84 */ 0x7150da6f49b30f3eULL, /* EGL_EXT_create_context_robustness */
    /*   85 */ 0x2f6c882c1eab9296ULL, /* EGL_EXT_device_base */
    /*   86 */ 0x25ef29d5ba78dacbULL, /* EGL_EXT_device_drm */
    /*   87 */ 0x85d84ed980a0f6c3ULL, /* EGL_EXT_device_drm_render_node */
    /*   88 */ 0xbf886c3682e570aaULL, /* EGL_EXT_device_enumeration */
    /*   89 */ 0xbb95b050ecd18b71ULL, /* EGL_EXT_device_openwf */
    /*   90 */ 0x25e4685edc9371c5ULL, /* EGL_EXT_device_persistent_id */
    /*   91 */ 0x4c3836479bf75ba3ULL, /* EGL_EXT_device_query */
    /*   92 */ 0x0ec61ed2c29b6b7eULL, /* EGL_EXT_device_query_name */
    /*   93 */ 0xf8f8a54f12fe9ca2ULL, /* EGL_EXT_device_type */
    /*   94 */ 0xdbf00a0a59a03004ULL, /* EGL_EXT_display_alloc */
    /*   95 */ 0x1a98bf220bf010e1ULL, /* EGL_EXT_explicit_device */
    /*   96 */ 0x375b95889c713c9aULL, /* EGL_EXT_gl_colorspace_bt2020_hlg */
    /*   97 */ 0x5091e9def2327eeaULL, /* EGL_EXT_gl_colorspace_bt2020_linear */
    /*   98 */ 0xfc5bf7ce45097f02ULL, /* EGL_EXT_gl_colorspace_bt2020_pq */
    /*   99 */ 0xd63b77d8efe7c73eULL, /* EGL_EXT_gl_colorspace_display_p3 */
    /*  100 */ 0x24c124c0512e760aULL, /* EGL_EXT_gl_colorspace_display_p3_linear */
    /*  101 */ 0x46817a7a0934b21aULL, /* EGL_EXT_gl_colorspace_display_p3_passthrough */
    /*  102 */ 0x01e6ab8e204224c3ULL, /* EGL_EXT_gl_colorspace_scrgb */
    /*  103 */ 0x9d59eeae4c92e9f7ULL, /* EGL_EXT_gl_colorspace_scrgb_linear */
    /*  104 */ 0x0c3a9519d769be90ULL, /* EGL_EXT_image_dma_buf_import */
    /*  105 */ 0xa09fd39f9f1158a7ULL, /* EGL_EXT_image_dma_buf_import_modifiers */
    /*  106 */ 0x476226fa1413890aULL, /* EGL_EXT_image_gl_colorspace */
    /*  107 */ 0xa5c94b3fdd6261daULL, /* EGL_EXT_image_implicit_sync_control */
    /*  108 */ 0x9f0bdd4dde93e968ULL, /* EGL_EXT_multiview_window */
    /*  109 */ 0xd324b54bf6a35048ULL, /* EGL_EXT_output_base */
    /*  110 */ 0x0659adf490093fcbULL, /* EGL_EXT_output_drm */
    /*  111 */ 0x53a0e0b8eb5f3f00ULL, /* EGL_EXT_output_openwf */
    /*  112 */ 0xefb059a6e6841776ULL, /* EGL_EXT_pixel_format_float */
    /*  113 */ 0xa841b196d3768c24ULL, /* EGL_EXT_platform_base */
    /*  114 */ 0x8df4a934a55860dbULL, /* EGL_EXT_platform_device */
    /*  115 */ 0x27716290eb920120ULL, /* EGL_EXT_platform_wayland */
    /*  116 */ 0xe548f3fc71409c63ULL, /* EGL_EXT_platform_x11 */
    /*  117 */ 0x6b5d9de25dfe7ebaULL, /* EGL_EXT_platform_xcb */
    /*  118 */ 0x5e7a56764d6c44b1ULL, /* EGL_EXT_present_opaque */
    /*  119 */ 0x91cb4ebfba10a35fULL, /* EGL_EXT_protected_content */
    /*  120 */ 0x83f096c0f29ebb18ULL, /* EGL_EXT_protected_surface */
    /*  121 */ 0xfd8d9ef9e9360c00ULL, /* EGL_EXT_query_reset_notification_strategy */
    /*  122 */ 0xfbac73bd87a06d67ULL, /* EGL_EXT_stream_consumer_egloutput */
    /*  123 */ 0x5654a8bc12eeebabULL, /* EGL_EXT_surface_CTA861_3_metadata */
    /*  124 */ 0x283ef3c9e93fa780ULL, /* EGL_EXT_surface_SMPTE2086_metadata */
    /*  125 */ 0x46e2ba77cc14c6daULL, /* EGL_EXT_surface_compression */
    /*  126 */ 0xff56e7e2acee3106ULL, /* EGL_EXT_swap_buffers_with_damage */
    /*  127 */ 0x42a3ca98a3fcecb6ULL, /* EGL_EXT_sync_reuse */
    /*  128 */ 0x451b691d8d24df6cULL, /* EGL_EXT_yuv_surface */
    /*  129 */ 0xdaf189f7653009bfULL, /* EGL_HI_clientpixmap */
    /*  130 */ 0x066d89176cab3c2cULL, /* EGL_HI_colorformats */
    /*  131 */ 0x0a76d8252afa230aULL, /* EGL_IMG_context_priority */
    /*  132 */ 0x7084567bc80e8320ULL, /* EGL_IMG_image_plane_attribs */
    /*  133 */ 0x0b5d7506753789deULL, /* EGL_KHR_cl_event */
    /*  134 */ 0x70fce70cba139c12ULL, /* EGL_KHR_cl_event2 */
    /*  135 */ 0xef7264f8eef3335bULL, /* EGL_KHR_client_get_all_proc_addresses */
    /*  136 */ 0x270d8abedb2d3a6dULL, /* EGL_KHR_config_attribs */
    /*  137 */ 0xda20b827ff8ca001ULL, /* EGL_KHR_context_flush_control */
    /*  138 */ 0x4e16c8c1f6a8131cULL, /* EGL_KHR_create_context */
    /*  139 */ 0x7b8ef4b379c8f0fdULL, /* EGL_KHR_create_context_no_error */
    /*  140 */ 0x5b61d2012f7861b3ULL, /* EGL_KHR_debug */
    /*  141 */ 0xfb4d4422d07bc81cULL, /* EGL_KHR_display_reference */
    /*  142 */ 0x3fc685858cb02200ULL, /* EGL_KHR_fence_sync */
    /*  143 */ 0xcc74201669ca5b5dULL, /* EGL_KHR_get_all_proc_addresses */
    /*  144 */ 0x0089c927779cc6efULL, /* EGL_KHR_gl_colorspace */
    /*  145 */ 0xf2fdf97c1361d5d7ULL, /* EGL_KHR_gl_renderbuffer_image */
    /*  146 */ 0x16756bf4b09c5e40ULL, /* EGL_KHR_gl_texture_2D_image */
    /*  147 */ 0x38fe09b43c8ef819ULL, /* EGL_KHR_gl_texture_3D_image */
    /*  148 */ 0x8da10d2afff88da2ULL, /* EGL_KHR_gl_texture_cubemap_image */
    /*  149 */ 0x871bd75821391394ULL, /* EGL_KHR_image */
    /*  150 */ 0xa2aecd33728540cbULL, /* EGL_KHR_image_base */
    /*  151 */ 0x6d3e7071805da5a8ULL, /* EGL_KHR_image_pixmap */
    /*  152 */ 0xd1965fc59df1967cULL, /* EGL_KHR_lock_surface */
    /*  153 */ 0x607598bc0d7426f5ULL, /* EGL_KHR_lock_surface2 */
    /*  154 */ 0xc5c0850bfdef920fULL, /* EGL_KHR_lock_surface3 */
    /*  155 */ 0xf2c65c6b58412a19ULL, /* EGL_KHR_mutable_render_buffer */
    /*  156 */ 0xb04bf399be660bcaULL, /* EGL_KHR_no_config_context */
    /*  157 */ 0xbf10c896f39ac381ULL, /* EGL_KHR_partial_update */
    /*  158 */ 0x1b60d04af505e88cULL, /* EGL_KHR_platform_android */
    /*  159 */ 0x92732717613804d7ULL, /* EGL_KHR_platform_gbm */
    /*  160 */ 0xa9c339bb0bd9f8ffULL, /* EGL_KHR_platform_wayland */
    /*  161 */ 0xb95b474e87d914c0ULL, /* EGL_KHR_platform_x11 */
    /*  162 */ 0x3e707e46a988246fULL, /* EGL_KHR_reusable_sync */
    /*  163 */ 0x16184f4f924509efULL, /* EGL_KHR_stream */
    /*  164 */ 0x9d0b59cf206f7842ULL, /* EGL_KHR_stream_attrib */
    /*  165 */ 0xd9b572ac9eb89474ULL, /* EGL_KHR_stream_consumer_gltexture */
    /*  166 */ 0x6e523fb6f05a3d29ULL, /* EGL_KHR_stream_cross_process_fd */
    /*  167 */ 0x3114241b811aadf2ULL, /* EGL_KHR_stream_fifo */
    /*  168 */ 0x4e02a91ae238a029ULL, /* EGL_KHR_stream_producer_aldatalocator */
    /*  169 */ 0x75e923758d9b47fbULL, /* EGL_KHR_stream_producer_eglsurface */
    /*  170 */ 0x98778891a458759fULL, /* EGL_KHR_surfaceless_context */
    /*  171 */ 0x836da10ce92250efULL, /* EGL_KHR_swap_buffers_with_damage */
    /*  172 */ 0xc795b75646aecc5bULL, /* EGL_KHR_vg_parent_image */
    /*  173 */ 0x76eb9817e8dc6c57ULL, /* EGL_KHR_wait_sync */
    /*  174 */ 0x8a02851eceb4e60bULL, /* EGL_MESA_drm_image */
    /*  175 */ 0xff40140d7e6b5b22ULL, /* EGL_MESA_image_dma_buf_export */
    /*  176 */ 0xcbf9865290d1d737ULL, /* EGL_MESA_platform_gbm */
    /*  177 */ 0xa718f1a00dfc77b2ULL, /* EGL_MESA_platform_surfaceless */
    /*  178 */ 0x205a0c44642ecfe4ULL, /* EGL_MESA_query_driver */
    /*  179 */ 0xc6c6646757ff2eb0ULL, /* EGL_NOK_swap_region */
    /*  180 */ 0xcacecd1071a7c53dULL, /* EGL_NOK_swap_region2 */
    /*  181 */ 0x140a1d4d56e89998ULL, /* EGL_NOK_texture_from_pixmap */
    /*  182 */ 0x53d1f2866df11721ULL, /* EGL_NV_3dvision_surface */
    /*  183 */ 0x87d534f485d23e03ULL, /* EGL_NV_context_priority_realtime */
    /*  184 */ 0x29d02d6b41d01c44ULL, /* EGL_NV_coverage_sample */
    /*  185 */ 0xbf4228511c15c43eULL, /* EGL_NV_coverage_sample_resolve */
    /*  186 */ 0xba24ab7c282aa98cULL, /* EGL_NV_cuda_event */
    /*  187 */ 0x4f20169819f31a19ULL, /* EGL_NV_depth_nonlinear */
    /*  188 */ 0xb32a3dd6b03226f2ULL, /* EGL_NV_device_cuda */
    /*  189 */ 0x797c903a522c4c75ULL, /* EGL_NV_native_query */
    /*  190 */ 0xb151fe3f08ba15f6ULL, /* EGL_NV_post_convert_rounding */
    /*  191 */ 0xaad3806034d0954dULL, /* EGL_NV_post_sub_buffer */
    /*  192 */ 0x37a228d0850f64a1ULL, /* EGL_NV_quadruple_buffer */
    /*  193 */ 0x74855b1caf0bb727ULL, /* EGL_NV_robustness_video_memory_purge */
    /*  194 */ 0x2db9bc2b87115201ULL, /* EGL_NV_stream_consumer_eglimage */
    /*  195 */ 0xd01bc63b758f4cb9ULL, /* EGL_NV_stream_consumer_eglimage_use_scanout_attrib */
    /*  196 */ 0x2baced719176deedULL, /* EGL_NV_stream_consumer_gltexture_yuv */
    /*  197 */ 0xfc105cd6c3f68dbeULL, /* EGL_NV_stream_cross_display */
    /*  198 */ 0x363e000d3383a473ULL, /* EGL_NV_stream_cross_object */
    /*  199 */ 0xac63132cd757c637ULL, /* EGL_NV_stream_cross_partition */
    /*  200 */ 0x2821ab7eeb491706ULL, /* EGL_NV_stream_cross_process */
    /*  201 */ 0x97b15fd0e09adf80ULL, /* EGL_NV_stream_cross_system */
    /*  202 */ 0x7ae84605ae3ae44aULL, /* EGL_NV_stream_dma */
    /*  203 */ 0x450721831a3bcf73ULL, /* EGL_NV_stream_fifo_next */
    /*  204 */ 0x5dd63931ba6563fbULL, /* EGL_NV_stream_fifo_synchronous */
    /*  205 */ 0x33597e019cc7811dULL, /* EGL_NV_stream_flush */
    /*  206 */ 0x0c5d5d4b9e76b0d3ULL, /* EGL_NV_stream_frame_limits */
    /*  207 */ 0xd899fb78ae205e27ULL, /* EGL_NV_stream_metadata */
    /*  208 */ 0xcb6e884a7e412a07ULL, /* EGL_NV_stream_origin */
    /*  209 */ 0x817f41736f96de51ULL, /* EGL_NV_stream_remote */
    /*  210 */ 0x6ad8d08948340894ULL, /* EGL_NV_stream_reset */
    /*  211 */ 0xb46eaf4ddee294f4ULL, /* EGL_NV_stream_socket */
    /*  212 */ 0x7d669bb43a324d63ULL, /* EGL_NV_stream_socket_inet */
    /*  213 */ 0x55bf7befb5997e09ULL, /* EGL_NV_stream_socket_unix */
    /*  214 */ 0xdfb98789892372ebULL, /* EGL_NV_stream_sync */
    /*  215 */ 0x5557f40f2ef2066cULL, /* EGL_NV_sync */
    /*  216 */ 0xe1a6732356a0f69fULL, /* EGL_NV_system_time */
    /*  217 */ 0xf2ec54e65029ed17ULL, /* EGL_NV_triple_buffer */
    /*  218 */ 0xaf15d314b7e55c0fULL, /* EGL_QNX_image_native_buffer */
    /*  219 */ 0x8efc13d2448ab5b1ULL, /* EGL_QNX_platform_screen */
    /*  220 */ 0x71dbd1513b2ad7e5ULL, /* EGL_TIZEN_image_native_buffer */
    /*  221 */ 0x6d7cb4f9ba09cb5dULL, /* EGL_TIZEN_image_native_surface */
    /*  222 */ 0xc81b6f913740e456ULL, /* EGL_WL_bind_wayland_display */
    /*  223 */ 0xa3002402543e70a5ULL  /* EGL_WL_create_wayland_buffer_from_image */
};

/* ---- Feature PFN range table ---------------------------------------------
 * Each entry maps one feature (by featArray index) to a contiguous run of
 * pfnArray slots. The loader iterates this table and bulk-loads the run
 * when featArray[entry.extension] is set.
 */
static const GloamPfnRange_t kFeatPfnRanges_EGL[] = {
    {    0,    0,   24 }, /* EGL_VERSION_1_0 */
    {    1,   24,    4 }, /* EGL_VERSION_1_1 */
    {    2,   28,    5 }, /* EGL_VERSION_1_2 */
    {    4,   33,    1 }, /* EGL_VERSION_1_4 */
    {    5,   34,   10 }, /* EGL_VERSION_1_5 */
};

/* ---- PFN range helper (GL / EGL / GLX / WGL) ----------------------------
 * Walks a contiguous run of pfnArray slots and calls the plain load callback
 * (name only) for each one.
 */
static void gloam_load_pfn_range_egl(GloamEGLContext *context, GloamLoadFunc getProcAddr, uint16_t start, uint16_t count)
{
    uint16_t i;
    for (i = start; i < (uint16_t)(start + count); ++i) {
        const char *pfnName = &kFnNameData_EGL[kFnNameOffsets_EGL[i]];
        context->pfnArray[i] = (void *)getProcAddr(pfnName);
    }
}

/* ---- Alias resolution table ----------------------------------------------
 * Pairs are sorted by canonical index so same-canonical entries are
 * consecutive; the resolver processes them in a single forward pass.
 */
static const GloamAliasPair_t kAliases_EGL[] = {
    {   34,   83 }, /* eglClientWaitSync and eglClientWaitSyncKHR */
    {   38,   78 }, /* eglCreateSync and eglCreateSync64KHR */
    {   39,   88 }, /* eglDestroyImage and eglDestroyImageKHR */
    {   40,   85 }, /* eglDestroySync and eglDestroySyncKHR */
    {   60,   82 }, /* eglQueryDisplayAttribEXT and eglQueryDisplayAttribKHR */
    {  131,   82 }, /* eglQueryDisplayAttribNV and eglQueryDisplayAttribKHR */
};

GLOAM_NO_INLINE static void gloam_resolve_aliases_egl(GloamEGLContext *context)
{
    uint32_t i;
    for (i = 0; i < GLOAM_ARRAYSIZE(kAliases_EGL); ++i) {
        uint16_t ci = kAliases_EGL[i].first;
        uint16_t si = kAliases_EGL[i].second;
        if (!context->pfnArray[ci] && context->pfnArray[si])
            context->pfnArray[ci] = context->pfnArray[si];
        else if (context->pfnArray[ci] && !context->pfnArray[si])
            context->pfnArray[si] = context->pfnArray[ci];
    }
}

/* ==========================================================================
 * Per-API sections
 * ==========================================================================
 */

/* --------------------------------------------------------------------------
 * API: egl
 * --------------------------------------------------------------------------
 */

/* Extension index subset for egl: extArray indices this API supports. */
static const uint16_t kExtIdx_egl[] = {
       0, /* EGL_ANDROID_GLES_layers */
       1, /* EGL_ANDROID_blob_cache */
       2, /* EGL_ANDROID_create_native_client_buffer */
       3, /* EGL_ANDROID_framebuffer_target */
       4, /* EGL_ANDROID_front_buffer_auto_refresh */
       5, /* EGL_ANDROID_get_frame_timestamps */
       6, /* EGL_ANDROID_get_native_client_buffer */
       7, /* EGL_ANDROID_image_native_buffer */
       8, /* EGL_ANDROID_native_fence_sync */
       9, /* EGL_ANDROID_presentation_time */
      10, /* EGL_ANDROID_recordable */
      11, /* EGL_ANDROID_telemetry_hint */
      12, /* EGL_ANGLE_colorspace_attribute_passthrough */
      13, /* EGL_ANGLE_context_virtualization */
      14, /* EGL_ANGLE_create_context_backwards_compatible */
      15, /* EGL_ANGLE_create_context_client_arrays */
      16, /* EGL_ANGLE_create_context_extensions_enabled */
      17, /* EGL_ANGLE_create_context_webgl_compatibility */
      18, /* EGL_ANGLE_create_surface_swap_interval */
      19, /* EGL_ANGLE_d3d_share_handle_client_buffer */
      20, /* EGL_ANGLE_d3d_texture_client_buffer */
      21, /* EGL_ANGLE_device_cgl */
      22, /* EGL_ANGLE_device_creation */
      23, /* EGL_ANGLE_device_d3d */
      24, /* EGL_ANGLE_device_d3d11 */
      25, /* EGL_ANGLE_device_d3d9 */
      26, /* EGL_ANGLE_device_eagl */
      27, /* EGL_ANGLE_device_metal */
      28, /* EGL_ANGLE_device_vulkan */
      29, /* EGL_ANGLE_direct_composition */
      30, /* EGL_ANGLE_display_power_preference */
      31, /* EGL_ANGLE_display_semaphore_share_group */
      32, /* EGL_ANGLE_display_texture_share_group */
      33, /* EGL_ANGLE_experimental_present_path */
      34, /* EGL_ANGLE_external_context_and_surface */
      35, /* EGL_ANGLE_feature_control */
      36, /* EGL_ANGLE_global_fence_sync */
      37, /* EGL_ANGLE_iosurface_client_buffer */
      38, /* EGL_ANGLE_keyed_mutex */
      39, /* EGL_ANGLE_memory_usage_report */
      40, /* EGL_ANGLE_metal_commands_scheduled_sync */
      41, /* EGL_ANGLE_metal_create_context_ownership_identity */
      42, /* EGL_ANGLE_metal_shared_event_sync */
      43, /* EGL_ANGLE_metal_texture_client_buffer */
      44, /* EGL_ANGLE_no_error */
      45, /* EGL_ANGLE_platform_angle */
      46, /* EGL_ANGLE_platform_angle_d3d */
      47, /* EGL_ANGLE_platform_angle_d3d11on12 */
      48, /* EGL_ANGLE_platform_angle_d3d_luid */
      49, /* EGL_ANGLE_platform_angle_device_context_volatile_cgl */
      50, /* EGL_ANGLE_platform_angle_device_context_volatile_eagl */
      51, /* EGL_ANGLE_platform_angle_device_id */
      52, /* EGL_ANGLE_platform_angle_device_type_egl */
      53, /* EGL_ANGLE_platform_angle_device_type_swiftshader */
      54, /* EGL_ANGLE_platform_angle_metal */
      55, /* EGL_ANGLE_platform_angle_null */
      56, /* EGL_ANGLE_platform_angle_opengl */
      57, /* EGL_ANGLE_platform_angle_vulkan */
      58, /* EGL_ANGLE_platform_angle_vulkan_device_uuid */
      59, /* EGL_ANGLE_platform_angle_webgpu */
      60, /* EGL_ANGLE_power_preference */
      61, /* EGL_ANGLE_prepare_swap_buffers */
      62, /* EGL_ANGLE_program_cache_control */
      63, /* EGL_ANGLE_query_surface_pointer */
      64, /* EGL_ANGLE_robust_resource_initialization */
      65, /* EGL_ANGLE_stream_producer_d3d_texture */
      66, /* EGL_ANGLE_surface_d3d_texture_2d_share_handle */
      67, /* EGL_ANGLE_surface_orientation */
      68, /* EGL_ANGLE_sync_control_rate */
      69, /* EGL_ANGLE_vulkan_display */
      70, /* EGL_ANGLE_vulkan_image */
      71, /* EGL_ANGLE_wait_until_work_scheduled */
      72, /* EGL_ANGLE_window_fixed_size */
      73, /* EGL_ANGLE_x11_visual */
      74, /* EGL_ARM_image_format */
      75, /* EGL_ARM_implicit_external_sync */
      76, /* EGL_ARM_pixmap_multisample_discard */
      77, /* EGL_CHROMIUM_sync_control */
      78, /* EGL_EXT_bind_to_front */
      79, /* EGL_EXT_buffer_age */
      80, /* EGL_EXT_client_extensions */
      81, /* EGL_EXT_client_sync */
      82, /* EGL_EXT_compositor */
      83, /* EGL_EXT_config_select_group */
      84, /* EGL_EXT_create_context_robustness */
      85, /* EGL_EXT_device_base */
      86, /* EGL_EXT_device_drm */
      87, /* EGL_EXT_device_drm_render_node */
      88, /* EGL_EXT_device_enumeration */
      89, /* EGL_EXT_device_openwf */
      90, /* EGL_EXT_device_persistent_id */
      91, /* EGL_EXT_device_query */
      92, /* EGL_EXT_device_query_name */
      93, /* EGL_EXT_device_type */
      94, /* EGL_EXT_display_alloc */
      95, /* EGL_EXT_explicit_device */
      96, /* EGL_EXT_gl_colorspace_bt2020_hlg */
      97, /* EGL_EXT_gl_colorspace_bt2020_linear */
      98, /* EGL_EXT_gl_colorspace_bt2020_pq */
      99, /* EGL_EXT_gl_colorspace_display_p3 */
     100, /* EGL_EXT_gl_colorspace_display_p3_linear */
     101, /* EGL_EXT_gl_colorspace_display_p3_passthrough */
     102, /* EGL_EXT_gl_colorspace_scrgb */
     103, /* EGL_EXT_gl_colorspace_scrgb_linear */
     104, /* EGL_EXT_image_dma_buf_import */
     105, /* EGL_EXT_image_dma_buf_import_modifiers */
     106, /* EGL_EXT_image_gl_colorspace */
     107, /* EGL_EXT_image_implicit_sync_control */
     108, /* EGL_EXT_multiview_window */
     109, /* EGL_EXT_output_base */
     110, /* EGL_EXT_output_drm */
     111, /* EGL_EXT_output_openwf */
     112, /* EGL_EXT_pixel_format_float */
     113, /* EGL_EXT_platform_base */
     114, /* EGL_EXT_platform_device */
     115, /* EGL_EXT_platform_wayland */
     116, /* EGL_EXT_platform_x11 */
     117, /* EGL_EXT_platform_xcb */
     118, /* EGL_EXT_present_opaque */
     119, /* EGL_EXT_protected_content */
     120, /* EGL_EXT_protected_surface */
     121, /* EGL_EXT_query_reset_notification_strategy */
     122, /* EGL_EXT_stream_consumer_egloutput */
     123, /* EGL_EXT_surface_CTA861_3_metadata */
     124, /* EGL_EXT_surface_SMPTE2086_metadata */
     125, /* EGL_EXT_surface_compression */
     126, /* EGL_EXT_swap_buffers_with_damage */
     127, /* EGL_EXT_sync_reuse */
     128, /* EGL_EXT_yuv_surface */
     129, /* EGL_HI_clientpixmap */
     130, /* EGL_HI_colorformats */
     131, /* EGL_IMG_context_priority */
     132, /* EGL_IMG_image_plane_attribs */
     133, /* EGL_KHR_cl_event */
     134, /* EGL_KHR_cl_event2 */
     135, /* EGL_KHR_client_get_all_proc_addresses */
     136, /* EGL_KHR_config_attribs */
     137, /* EGL_KHR_context_flush_control */
     138, /* EGL_KHR_create_context */
     139, /* EGL_KHR_create_context_no_error */
     140, /* EGL_KHR_debug */
     141, /* EGL_KHR_display_reference */
     142, /* EGL_KHR_fence_sync */
     143, /* EGL_KHR_get_all_proc_addresses */
     144, /* EGL_KHR_gl_colorspace */
     145, /* EGL_KHR_gl_renderbuffer_image */
     146, /* EGL_KHR_gl_texture_2D_image */
     147, /* EGL_KHR_gl_texture_3D_image */
     148, /* EGL_KHR_gl_texture_cubemap_image */
     149, /* EGL_KHR_image */
     150, /* EGL_KHR_image_base */
     151, /* EGL_KHR_image_pixmap */
     152, /* EGL_KHR_lock_surface */
     153, /* EGL_KHR_lock_surface2 */
     154, /* EGL_KHR_lock_surface3 */
     155, /* EGL_KHR_mutable_render_buffer */
     156, /* EGL_KHR_no_config_context */
     157, /* EGL_KHR_partial_update */
     158, /* EGL_KHR_platform_android */
     159, /* EGL_KHR_platform_gbm */
     160, /* EGL_KHR_platform_wayland */
     161, /* EGL_KHR_platform_x11 */
     162, /* EGL_KHR_reusable_sync */
     163, /* EGL_KHR_stream */
     164, /* EGL_KHR_stream_attrib */
     165, /* EGL_KHR_stream_consumer_gltexture */
     166, /* EGL_KHR_stream_cross_process_fd */
     167, /* EGL_KHR_stream_fifo */
     168, /* EGL_KHR_stream_producer_aldatalocator */
     169, /* EGL_KHR_stream_producer_eglsurface */
     170, /* EGL_KHR_surfaceless_context */
     171, /* EGL_KHR_swap_buffers_with_damage */
     172, /* EGL_KHR_vg_parent_image */
     173, /* EGL_KHR_wait_sync */
     174, /* EGL_MESA_drm_image */
     175, /* EGL_MESA_image_dma_buf_export */
     176, /* EGL_MESA_platform_gbm */
     177, /* EGL_MESA_platform_surfaceless */
     178, /* EGL_MESA_query_driver */
     179, /* EGL_NOK_swap_region */
     180, /* EGL_NOK_swap_region2 */
     181, /* EGL_NOK_texture_from_pixmap */
     182, /* EGL_NV_3dvision_surface */
     183, /* EGL_NV_context_priority_realtime */
     184, /* EGL_NV_coverage_sample */
     185, /* EGL_NV_coverage_sample_resolve */
     186, /* EGL_NV_cuda_event */
     187, /* EGL_NV_depth_nonlinear */
     188, /* EGL_NV_device_cuda */
     189, /* EGL_NV_native_query */
     190, /* EGL_NV_post_convert_rounding */
     191, /* EGL_NV_post_sub_buffer */
     192, /* EGL_NV_quadruple_buffer */
     193, /* EGL_NV_robustness_video_memory_purge */
     194, /* EGL_NV_stream_consumer_eglimage */
     195, /* EGL_NV_stream_consumer_eglimage_use_scanout_attrib */
     196, /* EGL_NV_stream_consumer_gltexture_yuv */
     197, /* EGL_NV_stream_cross_display */
     198, /* EGL_NV_stream_cross_object */
     199, /* EGL_NV_stream_cross_partition */
     200, /* EGL_NV_stream_cross_process */
     201, /* EGL_NV_stream_cross_system */
     202, /* EGL_NV_stream_dma */
     203, /* EGL_NV_stream_fifo_next */
     204, /* EGL_NV_stream_fifo_synchronous */
     205, /* EGL_NV_stream_flush */
     206, /* EGL_NV_stream_frame_limits */
     207, /* EGL_NV_stream_metadata */
     208, /* EGL_NV_stream_origin */
     209, /* EGL_NV_stream_remote */
     210, /* EGL_NV_stream_reset */
     211, /* EGL_NV_stream_socket */
     212, /* EGL_NV_stream_socket_inet */
     213, /* EGL_NV_stream_socket_unix */
     214, /* EGL_NV_stream_sync */
     215, /* EGL_NV_sync */
     216, /* EGL_NV_system_time */
     217, /* EGL_NV_triple_buffer */
     218, /* EGL_QNX_image_native_buffer */
     219, /* EGL_QNX_platform_screen */
     220, /* EGL_TIZEN_image_native_buffer */
     221, /* EGL_TIZEN_image_native_surface */
     222, /* EGL_WL_bind_wayland_display */
     223, /* EGL_WL_create_wayland_buffer_from_image */
};

/* Extension PFN range table for egl. */
static const GloamPfnRange_t kExtPfnRanges_egl[] = {
    {    1,   44,    1 }, /* EGL_ANDROID_blob_cache */
    {    2,   45,    1 }, /* EGL_ANDROID_create_native_client_buffer */
    {    6,   46,    1 }, /* EGL_ANDROID_get_native_client_buffer */
    {    8,   47,    1 }, /* EGL_ANDROID_native_fence_sync */
    {    9,   48,    1 }, /* EGL_ANDROID_presentation_time */
    {    5,   49,    5 }, /* EGL_ANDROID_get_frame_timestamps */
    {   63,   54,    1 }, /* EGL_ANGLE_query_surface_pointer */
    {   68,   55,    1 }, /* EGL_ANGLE_sync_control_rate */
    {   81,   56,    1 }, /* EGL_EXT_client_sync */
    {   85,   57,    4 }, /* EGL_EXT_device_base */
    {   88,   57,    1 }, /* EGL_EXT_device_enumeration */
    {   91,   58,    3 }, /* EGL_EXT_device_query */
    {  105,   61,    2 }, /* EGL_EXT_image_dma_buf_import_modifiers */
    {  109,   63,    8 }, /* EGL_EXT_output_base */
    {  113,   71,    3 }, /* EGL_EXT_platform_base */
    {  122,   74,    1 }, /* EGL_EXT_stream_consumer_egloutput */
    {  126,   75,    1 }, /* EGL_EXT_swap_buffers_with_damage */
    {  127,   76,    1 }, /* EGL_EXT_sync_reuse */
    {  129,   77,    1 }, /* EGL_HI_clientpixmap */
    {  134,   78,    1 }, /* EGL_KHR_cl_event2 */
    {  140,   79,    3 }, /* EGL_KHR_debug */
    {  141,   82,    1 }, /* EGL_KHR_display_reference */
    {  142,   83,    4 }, /* EGL_KHR_fence_sync */
    {  149,   87,    2 }, /* EGL_KHR_image */
    {  150,   87,    2 }, /* EGL_KHR_image_base */
    {  152,   89,    2 }, /* EGL_KHR_lock_surface */
    {  154,   89,    3 }, /* EGL_KHR_lock_surface3 */
    {  157,   92,    1 }, /* EGL_KHR_partial_update */
    {  162,   83,    4 }, /* EGL_KHR_reusable_sync */
    {  162,   93,    1 }, /* EGL_KHR_reusable_sync */
    {  163,   94,    5 }, /* EGL_KHR_stream */
    {  164,   99,    5 }, /* EGL_KHR_stream_attrib */
    {  165,  104,    3 }, /* EGL_KHR_stream_consumer_gltexture */
    {  166,  107,    2 }, /* EGL_KHR_stream_cross_process_fd */
    {  167,  109,    1 }, /* EGL_KHR_stream_fifo */
    {  169,  110,    1 }, /* EGL_KHR_stream_producer_eglsurface */
    {  171,  111,    1 }, /* EGL_KHR_swap_buffers_with_damage */
    {  173,  112,    1 }, /* EGL_KHR_wait_sync */
    {  174,  113,    2 }, /* EGL_MESA_drm_image */
    {  175,  115,    2 }, /* EGL_MESA_image_dma_buf_export */
    {  178,  117,    2 }, /* EGL_MESA_query_driver */
    {  179,  119,    1 }, /* EGL_NOK_swap_region */
    {  180,  120,    1 }, /* EGL_NOK_swap_region2 */
    {  189,  121,    3 }, /* EGL_NV_native_query */
    {  191,  124,    1 }, /* EGL_NV_post_sub_buffer */
    {  196,  125,    1 }, /* EGL_NV_stream_consumer_gltexture_yuv */
    {  194,  126,    4 }, /* EGL_NV_stream_consumer_eglimage */
    {  205,  130,    1 }, /* EGL_NV_stream_flush */
    {  207,  131,    3 }, /* EGL_NV_stream_metadata */
    {  210,  134,    1 }, /* EGL_NV_stream_reset */
    {  214,  135,    1 }, /* EGL_NV_stream_sync */
    {  215,  136,    6 }, /* EGL_NV_sync */
    {  216,  142,    2 }, /* EGL_NV_system_time */
    {   82,  144,    7 }, /* EGL_EXT_compositor */
    {  125,  151,    1 }, /* EGL_EXT_surface_compression */
    {  222,  152,    3 }, /* EGL_WL_bind_wayland_display */
    {  223,  155,    1 }, /* EGL_WL_create_wayland_buffer_from_image */
    {   90,  156,    1 }, /* EGL_EXT_device_persistent_id */
    {   94,  157,    1 }, /* EGL_EXT_display_alloc */
    {   22,  158,    2 }, /* EGL_ANGLE_device_creation */
    {   35,  160,    2 }, /* EGL_ANGLE_feature_control */
    {   34,  162,    2 }, /* EGL_ANGLE_external_context_and_surface */
    {   65,  164,    2 }, /* EGL_ANGLE_stream_producer_d3d_texture */
    {   77,  166,    1 }, /* EGL_CHROMIUM_sync_control */
    {   62,  167,    4 }, /* EGL_ANGLE_program_cache_control */
    {   71,  171,    1 }, /* EGL_ANGLE_wait_until_work_scheduled */
    {   61,  172,    1 }, /* EGL_ANGLE_prepare_swap_buffers */
    {   60,  173,    4 }, /* EGL_ANGLE_power_preference */
    {   70,  177,    1 }, /* EGL_ANGLE_vulkan_image */
    {   28,  178,    2 }, /* EGL_ANGLE_device_vulkan */
    {   42,  180,    1 }, /* EGL_ANGLE_metal_shared_event_sync */
    {   44,  181,    1 }, /* EGL_ANGLE_no_error */
};

/* EGL: concatenate client extensions (EGL_NO_DISPLAY) and display
 * extensions, then hash the combined space-separated list.
 */
static int gloam_egl_get_extensions_egl(GloamEGLContext *context, EGLDisplay display, uint64_t **out_exts, uint32_t *out_num_exts)
{
    const char *client_str, *display_str;
    char *concat = NULL;
    size_t client_len, display_len;
    int result;

    if (!context->QueryString)
        return 0;

    /* Client extensions live at EGL_NO_DISPLAY. */
    client_str  = (const char *)context->QueryString(EGL_NO_DISPLAY, EGL_EXTENSIONS);
    display_str = (display == EGL_NO_DISPLAY) ? "" :
                  (const char *)context->QueryString(display, EGL_EXTENSIONS);

    if (!client_str)
        return 0;
    if (!display_str)
        return 0;

    client_len  = strlen(client_str);
    display_len = strlen(display_str);

    /* Concatenate with a space separator. */
    concat = (char *)malloc(client_len + display_len + 2);
    if (!concat)
        return 0;
    memcpy(concat, client_str, client_len);
    size_t pos = client_len;
    if (display_len) {
        if (client_len && client_str[client_len - 1] != ' ')
            concat[pos++] = ' ';
        memcpy(concat + pos, display_str, display_len);
        pos += display_len;
    }
    concat[pos] = '\0';

    result = gloam_hash_ext_string(concat, out_exts, out_num_exts);
    free(concat);
    return result;
}

/* Search pre-baked kExtHashes_EGL against the sorted driver hash list and set
 * extArray flags for every matching extension.
 */
static int gloam_egl_find_extensions_egl(GloamEGLContext *context, EGLDisplay display)
{
    uint64_t *exts = NULL;
    uint32_t  num_exts = 0, i;

    if (!gloam_egl_get_extensions_egl(context, display, &exts, &num_exts))
        return 0;

    for (i = 0; i < GLOAM_ARRAYSIZE(kExtIdx_egl); ++i) {
        const uint16_t extIdx = kExtIdx_egl[i];
        context->extArray[extIdx] = (unsigned char)gloam_hash_search(exts, num_exts, kExtHashes_EGL[extIdx]);
    }

    free(exts);
    return 1;
}

/* Parse the EGL version string from eglQueryString(display, EGL_VERSION). */
static int gloam_egl_find_core_egl(GloamEGLContext *context, EGLDisplay display)
{
    int major = 0, minor = 0;
    unsigned short version_value;
    const char *version;
    if (!context->QueryString)
        return 0;
    version = (const char *)context->QueryString(display, EGL_VERSION);
    if (!version)
        return 0;
    GLOAM_IMPL_UTIL_SSCANF(version, "%d.%d", &major, &minor);
    version_value = (unsigned short)((major << 8) | minor);

    context->VERSION_1_0 = (unsigned char)(version_value >= 0x0100);
    context->VERSION_1_1 = (unsigned char)(version_value >= 0x0101);
    context->VERSION_1_2 = (unsigned char)(version_value >= 0x0102);
    context->VERSION_1_3 = (unsigned char)(version_value >= 0x0103);
    context->VERSION_1_4 = (unsigned char)(version_value >= 0x0104);
    context->VERSION_1_5 = (unsigned char)(version_value >= 0x0105);

    return (int)version_value;
}

int gloamLoadEGLContext(GloamEGLContext *context, EGLDisplay display, GloamLoadFunc getProcAddr)
{
    int version;
    uint32_t i;
    GLOAM_UNUSED(kFnCount_EGL);

    memset(context, 0, sizeof(*context));

    /* Bootstrap: QueryString must be loaded before version detection. */
    context->QueryString = (PFNEGLQUERYSTRINGPROC)getProcAddr("eglQueryString");

    version = gloam_egl_find_core_egl(context, display);
    if (!version)
        return 0;

    /* Load PFNs for each enabled feature via the range table. */
    for (i = 0; i < GLOAM_ARRAYSIZE(kFeatPfnRanges_EGL); ++i) {
        const GloamPfnRange_t *r = &kFeatPfnRanges_EGL[i];
        if (context->featArray[r->extension])
            gloam_load_pfn_range_egl(context, getProcAddr, r->start, r->count);
    }

    if (!gloam_egl_find_extensions_egl(context, display))
        return 0;

    for (i = 0; i < GLOAM_ARRAYSIZE(kExtPfnRanges_egl); ++i) {
        const GloamPfnRange_t *r = &kExtPfnRanges_egl[i];
        if (context->extArray[r->extension])
            gloam_load_pfn_range_egl(context, getProcAddr, r->start, r->count);
    }

    gloam_resolve_aliases_egl(context);

    return version;
}

int gloamLoadEGL(EGLDisplay display, GloamLoadFunc getProcAddr)
{
    return gloamLoadEGLContext(&gloam_egl_context, display, getProcAddr);
}

/* ==========================================================================
 * Built-in loader (--loader)
 * ==========================================================================
 */
#ifndef GLOAM_LOADER_LIBRARY_C_
#define GLOAM_LOADER_LIBRARY_C_

#if defined(GLOAM_PLATFORM_WINDOWS)

static void *gloam_dlopen(const char *name)
{
    return (void *)LoadLibraryA(name);
}
static void gloam_dlclose(void *handle)
{
    FreeLibrary((HMODULE)handle);
}
static void *gloam_dlsym(void *handle, const char *name)
{
    return (void *)GetProcAddress((HMODULE)handle, name);
}

#else /* POSIX */

static void *gloam_dlopen(const char *name)
{
    return dlopen(name, RTLD_LAZY | RTLD_LOCAL);
}
static void gloam_dlclose(void *handle)
{
    dlclose(handle);
}
static void *gloam_dlsym(void *handle, const char *name)
{
    return dlsym(handle, name);
}

#endif /* GLOAM_PLATFORM_WINDOWS */

/* Try each name in turn; return the first handle that opens successfully. */
static void *gloam_open_library(const char * const *names, int count)
{
    int i;
    for (i = 0; i < count; ++i) {
        void *h = gloam_dlopen(names[i]);
        if (h) return h;
    }
    return NULL;
}

#endif /* GLOAM_LOADER_LIBRARY_C_ */


/* ---- EGL built-in loader ------------------------------------------------ */

static const char * const gloam_egl_lib_names[] = {
#if defined(__APPLE__)
    "libEGL.dylib",
#elif defined(GLOAM_PLATFORM_WINDOWS)
    "libEGL.dll", "EGL.dll",
#else
    "libEGL.so.1", "libEGL.so",
#endif
};

/* eglGetProcAddress has its own calling convention (declared in EGL headers as
 * PFNEGLGETPROCADDRESSPROC). Store it with the correct type so the call always
 * uses the right convention, even when the default differs (e.g. Win32).
 */
struct gloam_egl_load_userptr {
    void *handle;
    PFNEGLGETPROCADDRESSPROC get_proc_address;
};
static struct gloam_egl_load_userptr gloam_egl_load_state;

static GloamAPIProc gloam_egl_get_proc(const char *name)
{
    struct gloam_egl_load_userptr *u = &gloam_egl_load_state;
    GloamAPIProc result = (GloamAPIProc)gloam_dlsym(u->handle, name);
    if (!result && u->get_proc_address)
        result = u->get_proc_address(name);
    return result;
}


int gloamLoaderLoadEGLContext(GloamEGLContext *context, EGLDisplay display)
{
    int did_open = 0;
    int version;
    void *handle;

    handle = context->gloam_loader_handle;

    if (!handle) {
        handle = gloam_open_library(gloam_egl_lib_names, GLOAM_ARRAYSIZE(gloam_egl_lib_names));
        did_open = 1;
    }

    if (!handle)
        return 0;

    gloam_egl_load_state.handle = handle;
    gloam_egl_load_state.get_proc_address =
        (PFNEGLGETPROCADDRESSPROC)gloam_dlsym(handle, "eglGetProcAddress");

    if (!gloam_egl_load_state.get_proc_address) {
        if (did_open)
            gloam_dlclose(handle);
        return 0;
    }

    version = gloamLoadEGLContext(context, display, gloam_egl_get_proc);
    gloam_egl_load_state.handle = NULL;

    if (!version && did_open) {
        gloam_dlclose(handle);
        return 0;
    }

    context->gloam_loader_handle = handle;
    context->gloam_loader_owns_handle |= (uint8_t)did_open;

    return version;
}

int gloamLoaderLoadEGL(EGLDisplay display)
{
    return gloamLoaderLoadEGLContext(&gloam_egl_context, display);
}

void gloamLoaderUnloadEGLContext(GloamEGLContext *context)
{
    if (context->gloam_loader_handle && context->gloam_loader_owns_handle) {
        gloam_dlclose(context->gloam_loader_handle);
    }
    gloamLoaderResetEGLContext(context);
}

void gloamLoaderUnloadEGL(void)
{
    gloamLoaderUnloadEGLContext(&gloam_egl_context);
}

void gloamLoaderResetEGLContext(GloamEGLContext *context)
{
    memset(context, 0, sizeof(*context));
}

void gloamLoaderResetEGL(void)
{
    gloamLoaderResetEGLContext(&gloam_egl_context);
}

